#if EE_PLATFORM_LINUX
#include "EngineApplication_Linux.h"
#include "Engine/_Module/_AutoGenerated/TypeInfo/TypeRegistration.h"

#if defined(EE_WITH_SDL3)
    #include <SDL3/SDL.h>
#elif defined(EE_WITH_SDL2)
    #include <SDL2/SDL.h>
#endif

//-------------------------------------------------------------------------

namespace EE
{
    StandaloneEngine::StandaloneEngine( TFunction<bool( EE::String const& error )>&& errorHandler )
        : Engine( eastl::forward<TFunction<bool( EE::String const& error )>&&>( errorHandler ) )
    {
        m_modules.emplace_back( EE::New<GameModule>() );
    }

    void StandaloneEngine::RegisterTypes()
    {
        TypeSystem::Reflection::RegisterTypes( *m_pTypeRegistry );
    }

    void StandaloneEngine::UnregisterTypes()
    {
        TypeSystem::Reflection::UnregisterTypes( *m_pTypeRegistry );
    }

    void StandaloneEngine::PostInitialize()
    {
        m_pGameViewport = m_pEntityWorldManager->GetGameWorld()->CreateViewport( m_pRenderWindow );
        Float2 const newViewportDimensions( m_pRenderWindow->GetSwapchainSize() );
        m_pGameViewport->Resize( Float2::Zero, newViewportDimensions );
    }

    void StandaloneEngine::PreShutdown()
    {
        if ( m_pGameViewport != nullptr )
        {
            m_pEntityWorldManager->GetGameWorld()->DestroyViewport( m_pGameViewport );
        }
    }

    void StandaloneEngine::ResizeMainWindow( Int2 newMainWindowDimensions )
    {
        Engine::ResizeMainWindow( newMainWindowDimensions );
        if ( m_pGameViewport != nullptr )
        {
            Float2 const newWindowDimensions = Float2( newMainWindowDimensions );
            Int2 const newViewportDimensions( Math::CeilingToInt32( newWindowDimensions.m_x ), Math::CeilingToInt32( newWindowDimensions.m_y ) );
            EE_ASSERT( newViewportDimensions.m_x > 0 && newViewportDimensions.m_y > 0 );
            m_pGameViewport->Resize( Float2::Zero, newViewportDimensions );
        }
    }

    //-------------------------------------------------------------------------

    EngineApplication::EngineApplication()
        : LinuxApplication( "Esoterica Engine" )
        , m_engine( TFunction<bool( EE::String const& error )>( [this] ( String const& error )-> bool { return FatalError( error ); } ) )
    {}

    void EngineApplication::ResizeMainWindow( Int2 const& newWindowSize )
    {
        m_engine.ResizeMainWindow( newWindowSize );
    }

    void EngineApplication::ProcessSDLEvent( void* pSDLEvent )
    {
        #if defined(EE_WITH_SDL3) || defined(EE_WITH_SDL2)
        SDL_Event* pEvent = reinterpret_cast<SDL_Event*>( pSDLEvent );
        // Forward to engine input system if it's an input event
        // SDL key/mouse events are translated to generic InputMessage here
        // For now, pass raw event type as message ID
        uint32_t msg = (uint32_t) pEvent->type;
        uintptr_t wParam = 0;
        intptr_t lParam = 0;
        #if defined(EE_WITH_SDL3)
        if ( pEvent->type == SDL_EVENT_KEY_DOWN || pEvent->type == SDL_EVENT_KEY_UP )
        {
            wParam = (uintptr_t) pEvent->key.key;
            lParam = (intptr_t) pEvent->key.scancode;
        }
        else if ( pEvent->type == SDL_EVENT_MOUSE_MOTION )
        {
            wParam = (uintptr_t) pEvent->motion.state;
            lParam = (intptr_t) ( ( (int32_t) pEvent->motion.x << 16 ) | ( (int32_t) pEvent->motion.y & 0xFFFF ) );
        }
        #else
        if ( pEvent->type == SDL_KEYDOWN || pEvent->type == SDL_KEYUP )
        {
            wParam = (uintptr_t) pEvent->key.keysym.sym;
            lParam = (intptr_t) pEvent->key.keysym.scancode;
        }
        #endif
        m_engine.GetInputSystem()->ForwardInputMessageToInputDevices( { msg, wParam, lParam } );
        #else
        (void) pSDLEvent;
        #endif
    }

    bool EngineApplication::Initialize( int32_t argc, char** argv )
    {
        Int2 windowDimensions = m_windowSize;
        // Try to get size from SDL window if available
        #if defined(EE_WITH_SDL3) || defined(EE_WITH_SDL2)
        if ( m_pWindow != nullptr )
        {
            int w = 0, h = 0;
            SDL_GetWindowSize( m_pWindow, &w, &h );
            windowDimensions = Int2( w, h );
        }
        #endif

        if ( !m_engine.Initialize( argc, argv, windowDimensions ) )
        {
            return FatalError( "Failed to initialize engine" );
        }
        return true;
    }

    bool EngineApplication::Shutdown()
    {
        return m_engine.Shutdown();
    }

    bool EngineApplication::ApplicationLoop()
    {
        return m_engine.Update();
    }
}

//-------------------------------------------------------------------------

int main( int argc, char** argv )
{
    int result = 0;
    {
        EE::ApplicationGlobalState globalState;
        EE::EngineApplication engineApplication;
        result = engineApplication.Run( argc, argv );
    }
    return result;
}

#endif
