#!/usr/bin/env bash
set -euo pipefail
# BuildLinux.sh — helper para compilar Esoterica no Linux
# Uso: ./BuildLinux.sh [debug|release|shipping] [--clean]

CONFIG="${1:-debug}"
CLEAN=false
if [[ "${2:-}" == "--clean" ]]; then CLEAN=true; fi

case "$CONFIG" in
  debug)    PRESET="linux-debug" ;;
  release)  PRESET="linux-release" ;;
  shipping) PRESET="linux-shipping" ;;
  *) echo "Uso: $0 [debug|release|shipping] [--clean]"; exit 1 ;;
esac

if $CLEAN; then
  echo "[clean] removendo build/$PRESET"
  rm -rf "build/$PRESET"
fi

echo "[configure] cmake --preset $PRESET"
cmake --preset "$PRESET"

echo "[reflect] tentando gerar _AutoGenerated se necessário"
if [[ ! -d "Code/Base/_Module/_AutoGenerated" ]]; then
  echo "  -> Reflector não encontrado, tentando compilar..."
  cmake --build "build/$PRESET" --target EsotericaReflector --config Debug || true
  if [[ -f "build/$PRESET/x64_Debug/EsotericaReflector" ]]; then
    "build/$PRESET/x64_Debug/EsotericaReflector" -s Esoterica.slnx || echo "  (reflector falhou — continue mesmo assim)"
  fi
fi

echo "[build] cmake --build build/$PRESET --parallel"
cmake --build "build/$PRESET" --parallel "$(nproc)"

echo "[done] binários em build/$PRESET/x64_${CONFIG^}/"
ls -lh "build/$PRESET/x64_${CONFIG^}/" 2>/dev/null | head -n 20 || true
