#!/usr/bin/env bash
set -euo pipefail
# CompileShaders_Linux.sh — HLSL -> SPIR-V via DXC for Vulkan backend
# Requires: dxc (from Vulkan SDK or External/DirectXShaderCompiler) and spirv tools optional

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SHADER_SRC="$ROOT/Code/Engine/Render/Shaders"
SHADER_OUT="$ROOT/Code/Engine/_Module/_AutoGenerated/Shaders"

DXC="${DXC:-dxc}"
if ! command -v "$DXC" &>/dev/null; then
  if [[ -f "$ROOT/External/DirectXShaderCompiler/build/bin/dxc" ]]; then
    DXC="$ROOT/External/DirectXShaderCompiler/build/bin/dxc"
  elif [[ -f "/usr/bin/dxc" ]]; then
    DXC="/usr/bin/dxc"
  else
    echo "dxc not found — install Vulkan SDK or build External/DirectXShaderCompiler"
    exit 1
  fi
fi

echo "Using DXC: $DXC"
mkdir -p "$SHADER_OUT"

# Map HLSL shader model per stage; reuse flags from CompileShaders.bat logic if available
compile() {
  local src="$1"
  local profile="$2"
  local entry="${3:-main}"
  local out="$4"
  echo "  $src -> $out [$profile $entry]"
  "$DXC" -spirv -T "$profile" -E "$entry" -Fo "$out" "$src" -WX -Qstrip_reflect 2>&1 | head -n 20 || true
}

# Example: compile all .esf as pixel/vertex; .esh are headers included, not compiled directly
for f in "$SHADER_SRC"/*.esf "$SHADER_SRC"/**/*.esf; do
  [[ -f "$f" ]] || continue
  base="$(basename "$f" .esf)"
  # Heuristic: files containing "Compute" or "Dispatch" use cs_6_6, mesh uses ms_6_6/as_6_6, else ps_6_6
  if [[ "$base" == *"Compute"* || "$base" == *"Dispatch"* ]]; then
    compile "$f" "cs_6_6" "main" "$SHADER_OUT/${base}.spv"
  elif [[ "$base" == *"Mesh"* ]]; then
    compile "$f" "ms_6_6" "main" "$SHADER_OUT/${base}.spv"
  else
    compile "$f" "ps_6_6" "main" "$SHADER_OUT/${base}.spv"
  fi
done

echo "Done — SPIR-V in $SHADER_OUT"
