#if EE_PLATFORM_LINUX
#include "EditorApplication_Linux.h"
#include "EngineTools/_Module/_AutoGenerated/TypeInfo/TypeRegistration.h"
#include "EngineTools/Core/SystemDialogs.h"

#if defined(EE_WITH_SDL3)
    #include <SDL3/SDL.h>
#elif defined(EE_WITH_SDL2)
    #include <SDL2/SDL.h>
#endif

//-------------------------------------------------------------------------

namespace EE
{
    EditorEngine::EditorEngine( TFunction<bool( EE::String const& error )>&& errorHandler )
        : Engine( eastl::forward<TFunction<bool( EE::String const& error )>&&>( errorHandler ) )
    {
        m_modules.emplace_back( EE::New<EngineToolsModule>() );
        m_modules.emplace_back( EE::New<GameModule>() );
        m_modules.emplace_back( EE::New<GameToolsModule>() );
    }

    void EditorEngine::RegisterTypes()
    {
        TypeSystem::Reflection::RegisterTypes( *m_pTypeRegistry );
    }

    void EditorEngine::UnregisterTypes()
    {
        TypeSystem::Reflection::UnregisterTypes( *m_pTypeRegistry );
    }

    void EditorEngine::SetStartupMap( ResourceID const& mapID )
    {
        EE_ASSERT( mapID.IsValid() );
        static_cast<EditorUI*>( m_pToolsUI )->SetStartupMap( mapID );
    }

    //-------------------------------------------------------------------------

    EditorApplication::EditorApplication()
        : LinuxApplication( "Esoterica Editor", -1, -1, TBitFlags<InitOptions>( LinuxApplication::InitOptions::Borderless ) )
        , m_engine( TFunction<bool( String const& error )>( [this] ( String const& error )-> bool  { return FatalError( error ); } ) )
    {}

    void EditorApplication::GetBorderlessTitleBarInfo( Math::ScreenSpaceRectangle& outTitlebarRect, bool& isInteractibleWidgetHovered ) const
    {
        static_cast<EditorUI*>( m_engine.m_pToolsUI )->GetBorderlessTitleBarInfo( outTitlebarRect, isInteractibleWidgetHovered );
    }

    void EditorApplication::ResizeMainWindow( Int2 const& newWindowSize )
    {
        m_engine.ResizeMainWindow( newWindowSize );
    }

    void EditorApplication::ProcessSDLEvent( void* pSDLEvent )
    {
        #if defined(EE_WITH_SDL3) || defined(EE_WITH_SDL2)
        SDL_Event* pEvent = reinterpret_cast<SDL_Event*>( pSDLEvent );
        uint32_t msg = (uint32_t) pEvent->type;
        uintptr_t wParam = 0;
        intptr_t lParam = 0;
        m_engine.GetInputSystem()->ForwardInputMessageToInputDevices( { msg, wParam, lParam } );
        #else
        (void) pSDLEvent;
        #endif
    }

    bool EditorApplication::Initialize( int32_t argc, char** argv )
    {
        Int2 windowDimensions = m_windowSize;
        #if defined(EE_WITH_SDL3) || defined(EE_WITH_SDL2)
        if ( m_pWindow != nullptr )
        {
            int w = 0, h = 0;
            SDL_GetWindowSize( m_pWindow, &w, &h );
            windowDimensions = Int2( w, h );
        }
        #endif

        if ( !m_engine.Initialize( argc, argv, windowDimensions ) )
        {
            return false;
        }
        return true;
    }

    bool EditorApplication::Shutdown()
    {
        return m_engine.Shutdown();
    }

    bool EditorApplication::FatalError( String const& error ) const
    {
        if ( m_engine.m_pToolsUI != nullptr )
        {
            // On Linux, use console + SDL message box fallback
            fprintf( stderr, "Fatal Error: %s\n", error.c_str() );
            #if defined(EE_WITH_SDL3) || defined(EE_WITH_SDL2)
            SDL_ShowSimpleMessageBox( SDL_MESSAGEBOX_ERROR, "Fatal Error Occurred", error.c_str(), m_pWindow );
            #endif
            return false;
        }
        else
        {
            return LinuxApplication::FatalError( error );
        }
    }

    bool EditorApplication::ApplicationLoop()
    {
        return m_engine.Update();
    }
}

//-------------------------------------------------------------------------

int main( int argc, char** argv )
{
    int32_t result = 0;
    {
        EE::ApplicationGlobalState globalState;
        EE::EditorApplication editorApplication;
        result = editorApplication.Run( argc, argv );
    }
    return result;
}

#endif
